name: Deploy to Render

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Render CLI
        run: |
          curl -fsSL https://cli.render.com/install.sh | bash
          echo "$HOME/.render/bin" >> $GITHUB_PATH
      
      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          render services deploy $RENDER_SERVICE_ID \
            --dockerfilePath ./Dockerfile \
            --buildArgs NODE_ENV=production